name: Update CONTRIBUTORS file
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo <<EOF > CONTRIBUTORS.md
          # Contributors

          Shout out to our top contributors!

          EOF

          echo $(gh api repos/polatengin/athens/contributors --jq 'map(select(.login | endswith("[bot]") | not)) | .[].login') >> CONTRIBUTORS.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
